/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class UI */

#ifndef _Included_UI
#define _Included_UI
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     UI
 * Method:    constructConnection
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_UI_constructConnection
  (JNIEnv *, jobject);

/*
 * Class:     UI
 * Method:    addPart
 * Signature: (Ljava/lang/String;Ljava/lang/String;Ljava/lang/String;Ljava/lang/String;)Z
 */
JNIEXPORT jboolean JNICALL Java_UI_addPart
  (JNIEnv *, jobject, jstring, jstring, jstring, jstring);

#ifdef __cplusplus
}
#endif
#endif
