/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 3.0.12
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package mypackage;

public class Connection {
  private transient long swigCPtr;
  protected transient boolean swigCMemOwn;

  protected Connection(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(Connection obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        testJNI.delete_Connection(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public Connection() {
    this(testJNI.new_Connection(), true);
  }

  public Part addPart(int partNumber, int count, String name, String description) {
    long cPtr = testJNI.Connection_addPart(swigCPtr, this, partNumber, count, name, description);
    return (cPtr == 0) ? null : new Part(cPtr, false);
  }

  public Part searchPart(int partNumber) {
    long cPtr = testJNI.Connection_searchPart(swigCPtr, this, partNumber);
    return (cPtr == 0) ? null : new Part(cPtr, false);
  }

  public Part findPart(int partNumber) {
    long cPtr = testJNI.Connection_findPart(swigCPtr, this, partNumber);
    return (cPtr == 0) ? null : new Part(cPtr, false);
  }

  public boolean editPart(Part curr, int count, String name, String description) {
    return testJNI.Connection_editPart(swigCPtr, this, Part.getCPtr(curr), curr, count, name, description);
  }

  public boolean orderPart(Part curr, int count, String mechanic, String notes, int priority) {
    return testJNI.Connection_orderPart(swigCPtr, this, Part.getCPtr(curr), curr, count, mechanic, notes, priority);
  }

  public void printRequestQueue() {
    testJNI.Connection_printRequestQueue(swigCPtr, this);
  }

  public void printRequest(Request r) {
    testJNI.Connection_printRequest(swigCPtr, this, Request.getCPtr(r), r);
  }

  public void setTimeOpened(int value) {
    testJNI.Connection_timeOpened_set(swigCPtr, this, value);
  }

  public int getTimeOpened() {
    return testJNI.Connection_timeOpened_get(swigCPtr, this);
  }

}
