/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 3.0.12
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package mypackage;

public class ReplacementVector {
  private transient long swigCPtr;
  protected transient boolean swigCMemOwn;

  protected ReplacementVector(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(ReplacementVector obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        testJNI.delete_ReplacementVector(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public ReplacementVector() {
    this(testJNI.new_ReplacementVector__SWIG_0(), true);
  }

  public ReplacementVector(long n) {
    this(testJNI.new_ReplacementVector__SWIG_1(n), true);
  }

  public long size() {
    return testJNI.ReplacementVector_size(swigCPtr, this);
  }

  public long capacity() {
    return testJNI.ReplacementVector_capacity(swigCPtr, this);
  }

  public void reserve(long n) {
    testJNI.ReplacementVector_reserve(swigCPtr, this, n);
  }

  public boolean isEmpty() {
    return testJNI.ReplacementVector_isEmpty(swigCPtr, this);
  }

  public void clear() {
    testJNI.ReplacementVector_clear(swigCPtr, this);
  }

  public void add(Replacement x) {
    testJNI.ReplacementVector_add(swigCPtr, this, Replacement.getCPtr(x), x);
  }

  public Replacement get(int i) {
    return new Replacement(testJNI.ReplacementVector_get(swigCPtr, this, i), false);
  }

  public void set(int i, Replacement val) {
    testJNI.ReplacementVector_set(swigCPtr, this, i, Replacement.getCPtr(val), val);
  }

}
