/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 3.0.12
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package mypackage;

public class Replacement {
  private transient long swigCPtr;
  protected transient boolean swigCMemOwn;

  protected Replacement(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(Replacement obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        testJNI.delete_Replacement(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public void setDate(int value) {
    testJNI.Replacement_date_set(swigCPtr, this, value);
  }

  public int getDate() {
    return testJNI.Replacement_date_get(swigCPtr, this);
  }

  public void setMechanic(strmod value) {
    testJNI.Replacement_mechanic_set(swigCPtr, this, strmod.getCPtr(value), value);
  }

  public strmod getMechanic() {
    long cPtr = testJNI.Replacement_mechanic_get(swigCPtr, this);
    return (cPtr == 0) ? null : new strmod(cPtr, false);
  }

  public void setNotes(strmod value) {
    testJNI.Replacement_notes_set(swigCPtr, this, strmod.getCPtr(value), value);
  }

  public strmod getNotes() {
    long cPtr = testJNI.Replacement_notes_get(swigCPtr, this);
    return (cPtr == 0) ? null : new strmod(cPtr, false);
  }

  public Replacement() {
    this(testJNI.new_Replacement(), true);
  }

}
