/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 3.0.12
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package mypackage;

public class Request {
  private transient long swigCPtr;
  protected transient boolean swigCMemOwn;

  protected Request(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(Request obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        testJNI.delete_Request(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public void setDateRequested(SWIGTYPE_p_time_t value) {
    testJNI.Request_dateRequested_set(swigCPtr, this, SWIGTYPE_p_time_t.getCPtr(value));
  }

  public SWIGTYPE_p_time_t getDateRequested() {
    return new SWIGTYPE_p_time_t(testJNI.Request_dateRequested_get(swigCPtr, this), true);
  }

  public void setDateOrdered(SWIGTYPE_p_time_t value) {
    testJNI.Request_dateOrdered_set(swigCPtr, this, SWIGTYPE_p_time_t.getCPtr(value));
  }

  public SWIGTYPE_p_time_t getDateOrdered() {
    return new SWIGTYPE_p_time_t(testJNI.Request_dateOrdered_get(swigCPtr, this), true);
  }

  public void setDateFulfilled(SWIGTYPE_p_time_t value) {
    testJNI.Request_dateFulfilled_set(swigCPtr, this, SWIGTYPE_p_time_t.getCPtr(value));
  }

  public SWIGTYPE_p_time_t getDateFulfilled() {
    return new SWIGTYPE_p_time_t(testJNI.Request_dateFulfilled_get(swigCPtr, this), true);
  }

  public void setMechanic(strmod value) {
    testJNI.Request_mechanic_set(swigCPtr, this, strmod.getCPtr(value), value);
  }

  public strmod getMechanic() {
    long cPtr = testJNI.Request_mechanic_get(swigCPtr, this);
    return (cPtr == 0) ? null : new strmod(cPtr, false);
  }

  public void setNotes(strmod value) {
    testJNI.Request_notes_set(swigCPtr, this, strmod.getCPtr(value), value);
  }

  public strmod getNotes() {
    long cPtr = testJNI.Request_notes_get(swigCPtr, this);
    return (cPtr == 0) ? null : new strmod(cPtr, false);
  }

  public void setCount(int value) {
    testJNI.Request_count_set(swigCPtr, this, value);
  }

  public int getCount() {
    return testJNI.Request_count_get(swigCPtr, this);
  }

  public void setPriority(int value) {
    testJNI.Request_priority_set(swigCPtr, this, value);
  }

  public int getPriority() {
    return testJNI.Request_priority_get(swigCPtr, this);
  }

  public void setPartNumber(int value) {
    testJNI.Request_partNumber_set(swigCPtr, this, value);
  }

  public int getPartNumber() {
    return testJNI.Request_partNumber_get(swigCPtr, this);
  }

  public Request() {
    this(testJNI.new_Request__SWIG_0(), true);
  }

  public Request(SWIGTYPE_p_time_t dateRequested, SWIGTYPE_p_time_t dateOrdered, SWIGTYPE_p_time_t dateFulfilled, String mechanic, String notes, int count, int priority, int partNum) {
    this(testJNI.new_Request__SWIG_1(SWIGTYPE_p_time_t.getCPtr(dateRequested), SWIGTYPE_p_time_t.getCPtr(dateOrdered), SWIGTYPE_p_time_t.getCPtr(dateFulfilled), mechanic, notes, count, priority, partNum), true);
  }

}
