/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 4.0.1
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package mypackage;

public class Part {
  private transient long swigCPtr;
  protected transient boolean swigCMemOwn;

  protected Part(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(Part obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  @SuppressWarnings("deprecation")
  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        testJNI.delete_Part(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public void setPartNum(int value) {
    testJNI.Part_partNum_set(swigCPtr, this, value);
  }

  public int getPartNum() {
    return testJNI.Part_partNum_get(swigCPtr, this);
  }

  public void setCount(int value) {
    testJNI.Part_count_set(swigCPtr, this, value);
  }

  public int getCount() {
    return testJNI.Part_count_get(swigCPtr, this);
  }

  public void setName(strmod value) {
    testJNI.Part_name_set(swigCPtr, this, strmod.getCPtr(value), value);
  }

  public strmod getName() {
    long cPtr = testJNI.Part_name_get(swigCPtr, this);
    return (cPtr == 0) ? null : new strmod(cPtr, false);
  }

  public void setDescription(strmod value) {
    testJNI.Part_description_set(swigCPtr, this, strmod.getCPtr(value), value);
  }

  public strmod getDescription() {
    long cPtr = testJNI.Part_description_get(swigCPtr, this);
    return (cPtr == 0) ? null : new strmod(cPtr, false);
  }

  public void setRequests(RequestVector value) {
    testJNI.Part_requests_set(swigCPtr, this, RequestVector.getCPtr(value), value);
  }

  public RequestVector getRequests() {
    long cPtr = testJNI.Part_requests_get(swigCPtr, this);
    return (cPtr == 0) ? null : new RequestVector(cPtr, false);
  }

  public void setMachines(MachinePart value) {
    testJNI.Part_machines_set(swigCPtr, this, MachinePart.getCPtr(value), value);
  }

  public MachinePart getMachines() {
    long cPtr = testJNI.Part_machines_get(swigCPtr, this);
    return (cPtr == 0) ? null : new MachinePart(cPtr, false);
  }

  public Part() {
    this(testJNI.new_Part__SWIG_0(), true);
  }

  public Part(int partNumber, int count, String name, String description) {
    this(testJNI.new_Part__SWIG_1(partNumber, count, name, description), true);
  }

}
