/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 3.0.12
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package mypackage;

public class RequestPVector {
  private transient long swigCPtr;
  protected transient boolean swigCMemOwn;

  protected RequestPVector(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(RequestPVector obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        testJNI.delete_RequestPVector(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public RequestPVector() {
    this(testJNI.new_RequestPVector__SWIG_0(), true);
  }

  public RequestPVector(long n) {
    this(testJNI.new_RequestPVector__SWIG_1(n), true);
  }

  public long size() {
    return testJNI.RequestPVector_size(swigCPtr, this);
  }

  public long capacity() {
    return testJNI.RequestPVector_capacity(swigCPtr, this);
  }

  public void reserve(long n) {
    testJNI.RequestPVector_reserve(swigCPtr, this, n);
  }

  public boolean isEmpty() {
    return testJNI.RequestPVector_isEmpty(swigCPtr, this);
  }

  public void clear() {
    testJNI.RequestPVector_clear(swigCPtr, this);
  }

  public void add(Request x) {
    testJNI.RequestPVector_add(swigCPtr, this, Request.getCPtr(x), x);
  }

  public Request get(int i) {
    long cPtr = testJNI.RequestPVector_get(swigCPtr, this, i);
    return (cPtr == 0) ? null : new Request(cPtr, false);
  }

  public void set(int i, Request val) {
    testJNI.RequestPVector_set(swigCPtr, this, i, Request.getCPtr(val), val);
  }

}
