/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 3.0.12
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package mypackage;

public class PartPVector {
  private transient long swigCPtr;
  protected transient boolean swigCMemOwn;

  protected PartPVector(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(PartPVector obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        testJNI.delete_PartPVector(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public PartPVector() {
    this(testJNI.new_PartPVector__SWIG_0(), true);
  }

  public PartPVector(long n) {
    this(testJNI.new_PartPVector__SWIG_1(n), true);
  }

  public long size() {
    return testJNI.PartPVector_size(swigCPtr, this);
  }

  public long capacity() {
    return testJNI.PartPVector_capacity(swigCPtr, this);
  }

  public void reserve(long n) {
    testJNI.PartPVector_reserve(swigCPtr, this, n);
  }

  public boolean isEmpty() {
    return testJNI.PartPVector_isEmpty(swigCPtr, this);
  }

  public void clear() {
    testJNI.PartPVector_clear(swigCPtr, this);
  }

  public void add(Part x) {
    testJNI.PartPVector_add(swigCPtr, this, Part.getCPtr(x), x);
  }

  public Part get(int i) {
    long cPtr = testJNI.PartPVector_get(swigCPtr, this, i);
    return (cPtr == 0) ? null : new Part(cPtr, false);
  }

  public void set(int i, Part val) {
    testJNI.PartPVector_set(swigCPtr, this, i, Part.getCPtr(val), val);
  }

}
