/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 3.0.12
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package mypackage;

public class PartVector {
  private transient long swigCPtr;
  protected transient boolean swigCMemOwn;

  protected PartVector(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(PartVector obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        testJNI.delete_PartVector(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public PartVector() {
    this(testJNI.new_PartVector__SWIG_0(), true);
  }

  public PartVector(long n) {
    this(testJNI.new_PartVector__SWIG_1(n), true);
  }

  public long size() {
    return testJNI.PartVector_size(swigCPtr, this);
  }

  public long capacity() {
    return testJNI.PartVector_capacity(swigCPtr, this);
  }

  public void reserve(long n) {
    testJNI.PartVector_reserve(swigCPtr, this, n);
  }

  public boolean isEmpty() {
    return testJNI.PartVector_isEmpty(swigCPtr, this);
  }

  public void clear() {
    testJNI.PartVector_clear(swigCPtr, this);
  }

  public void add(Part x) {
    testJNI.PartVector_add(swigCPtr, this, Part.getCPtr(x), x);
  }

  public Part get(int i) {
    return new Part(testJNI.PartVector_get(swigCPtr, this, i), false);
  }

  public void set(int i, Part val) {
    testJNI.PartVector_set(swigCPtr, this, i, Part.getCPtr(val), val);
  }

}
