/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 3.0.12
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package mypackage;

public class ReplacementPVector {
  private transient long swigCPtr;
  protected transient boolean swigCMemOwn;

  protected ReplacementPVector(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(ReplacementPVector obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        testJNI.delete_ReplacementPVector(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public ReplacementPVector() {
    this(testJNI.new_ReplacementPVector__SWIG_0(), true);
  }

  public ReplacementPVector(long n) {
    this(testJNI.new_ReplacementPVector__SWIG_1(n), true);
  }

  public long size() {
    return testJNI.ReplacementPVector_size(swigCPtr, this);
  }

  public long capacity() {
    return testJNI.ReplacementPVector_capacity(swigCPtr, this);
  }

  public void reserve(long n) {
    testJNI.ReplacementPVector_reserve(swigCPtr, this, n);
  }

  public boolean isEmpty() {
    return testJNI.ReplacementPVector_isEmpty(swigCPtr, this);
  }

  public void clear() {
    testJNI.ReplacementPVector_clear(swigCPtr, this);
  }

  public void add(Replacement x) {
    testJNI.ReplacementPVector_add(swigCPtr, this, Replacement.getCPtr(x), x);
  }

  public Replacement get(int i) {
    long cPtr = testJNI.ReplacementPVector_get(swigCPtr, this, i);
    return (cPtr == 0) ? null : new Replacement(cPtr, false);
  }

  public void set(int i, Replacement val) {
    testJNI.ReplacementPVector_set(swigCPtr, this, i, Replacement.getCPtr(val), val);
  }

}
