/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 3.0.12
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package mypackage;

public class RequestVector {
  private transient long swigCPtr;
  protected transient boolean swigCMemOwn;

  protected RequestVector(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(RequestVector obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        testJNI.delete_RequestVector(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public RequestVector() {
    this(testJNI.new_RequestVector__SWIG_0(), true);
  }

  public RequestVector(long n) {
    this(testJNI.new_RequestVector__SWIG_1(n), true);
  }

  public long size() {
    return testJNI.RequestVector_size(swigCPtr, this);
  }

  public long capacity() {
    return testJNI.RequestVector_capacity(swigCPtr, this);
  }

  public void reserve(long n) {
    testJNI.RequestVector_reserve(swigCPtr, this, n);
  }

  public boolean isEmpty() {
    return testJNI.RequestVector_isEmpty(swigCPtr, this);
  }

  public void clear() {
    testJNI.RequestVector_clear(swigCPtr, this);
  }

  public void add(Request x) {
    testJNI.RequestVector_add(swigCPtr, this, Request.getCPtr(x), x);
  }

  public Request get(int i) {
    return new Request(testJNI.RequestVector_get(swigCPtr, this, i), false);
  }

  public void set(int i, Request val) {
    testJNI.RequestVector_set(swigCPtr, this, i, Request.getCPtr(val), val);
  }

}
