/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 3.0.12
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package mypackage;

public class SaveMethod {
  private transient long swigCPtr;
  protected transient boolean swigCMemOwn;

  protected SaveMethod(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(SaveMethod obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        testJNI.delete_SaveMethod(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public SaveMethod(String savDir) {
    this(testJNI.new_SaveMethod(savDir), true);
  }

  public void save(Connection A) {
    testJNI.SaveMethod_save(swigCPtr, this, Connection.getCPtr(A), A);
  }

  public Connection load(int savNum) {
    return new Connection(testJNI.SaveMethod_load(swigCPtr, this, savNum), true);
  }

  public void printSaveHistory() {
    testJNI.SaveMethod_printSaveHistory(swigCPtr, this);
  }

}
