/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 3.0.12
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package mypackage;

public class strmod {
  private transient long swigCPtr;
  protected transient boolean swigCMemOwn;

  protected strmod(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(strmod obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        testJNI.delete_strmod(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public strmod() {
    this(testJNI.new_strmod__SWIG_0(), true);
  }

  public strmod(String instr) {
    this(testJNI.new_strmod__SWIG_1(instr), true);
  }

  public void setStr(String instr) {
    testJNI.strmod_setStr(swigCPtr, this, instr);
  }

  public void apdStr(String apdstr) {
    testJNI.strmod_apdStr(swigCPtr, this, apdstr);
  }

  public String getStr() {
    return testJNI.strmod_getStr(swigCPtr, this);
  }

}
