/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 4.0.1
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package mypackage;

public class MachinePart {
  private transient long swigCPtr;
  protected transient boolean swigCMemOwn;

  protected MachinePart(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(MachinePart obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  @SuppressWarnings("deprecation")
  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        testJNI.delete_MachinePart(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public void setPartNum(int value) {
    testJNI.MachinePart_partNum_set(swigCPtr, this, value);
  }

  public int getPartNum() {
    return testJNI.MachinePart_partNum_get(swigCPtr, this);
  }

  public void setNotes(strmod value) {
    testJNI.MachinePart_notes_set(swigCPtr, this, strmod.getCPtr(value), value);
  }

  public strmod getNotes() {
    long cPtr = testJNI.MachinePart_notes_get(swigCPtr, this);
    return (cPtr == 0) ? null : new strmod(cPtr, false);
  }

  public void setReplacements(ReplacementVector value) {
    testJNI.MachinePart_replacements_set(swigCPtr, this, ReplacementVector.getCPtr(value), value);
  }

  public ReplacementVector getReplacements() {
    long cPtr = testJNI.MachinePart_replacements_get(swigCPtr, this);
    return (cPtr == 0) ? null : new ReplacementVector(cPtr, false);
  }

  public MachinePart() {
    this(testJNI.new_MachinePart(), true);
  }

}
