/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 4.0.1
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package mypackage;

public class PartPVector extends java.util.AbstractList<Part> implements java.util.RandomAccess {
  private transient long swigCPtr;
  protected transient boolean swigCMemOwn;

  protected PartPVector(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(PartPVector obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  @SuppressWarnings("deprecation")
  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        testJNI.delete_PartPVector(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public PartPVector(Part[] initialElements) {
    this();
    reserve(initialElements.length);

    for (Part element : initialElements) {
      add(element);
    }
  }

  public PartPVector(Iterable<Part> initialElements) {
    this();
    for (Part element : initialElements) {
      add(element);
    }
  }

  public Part get(int index) {
    return doGet(index);
  }

  public Part set(int index, Part e) {
    return doSet(index, e);
  }

  public boolean add(Part e) {
    modCount++;
    doAdd(e);
    return true;
  }

  public void add(int index, Part e) {
    modCount++;
    doAdd(index, e);
  }

  public Part remove(int index) {
    modCount++;
    return doRemove(index);
  }

  protected void removeRange(int fromIndex, int toIndex) {
    modCount++;
    doRemoveRange(fromIndex, toIndex);
  }

  public int size() {
    return doSize();
  }

  public PartPVector() {
    this(testJNI.new_PartPVector__SWIG_0(), true);
  }

  public PartPVector(PartPVector other) {
    this(testJNI.new_PartPVector__SWIG_1(PartPVector.getCPtr(other), other), true);
  }

  public long capacity() {
    return testJNI.PartPVector_capacity(swigCPtr, this);
  }

  public void reserve(long n) {
    testJNI.PartPVector_reserve(swigCPtr, this, n);
  }

  public boolean isEmpty() {
    return testJNI.PartPVector_isEmpty(swigCPtr, this);
  }

  public void clear() {
    testJNI.PartPVector_clear(swigCPtr, this);
  }

  public PartPVector(int count, Part value) {
    this(testJNI.new_PartPVector__SWIG_2(count, Part.getCPtr(value), value), true);
  }

  private int doSize() {
    return testJNI.PartPVector_doSize(swigCPtr, this);
  }

  private void doAdd(Part x) {
    testJNI.PartPVector_doAdd__SWIG_0(swigCPtr, this, Part.getCPtr(x), x);
  }

  private void doAdd(int index, Part x) {
    testJNI.PartPVector_doAdd__SWIG_1(swigCPtr, this, index, Part.getCPtr(x), x);
  }

  private Part doRemove(int index) {
    long cPtr = testJNI.PartPVector_doRemove(swigCPtr, this, index);
    return (cPtr == 0) ? null : new Part(cPtr, false);
  }

  private Part doGet(int index) {
    long cPtr = testJNI.PartPVector_doGet(swigCPtr, this, index);
    return (cPtr == 0) ? null : new Part(cPtr, false);
  }

  private Part doSet(int index, Part val) {
    long cPtr = testJNI.PartPVector_doSet(swigCPtr, this, index, Part.getCPtr(val), val);
    return (cPtr == 0) ? null : new Part(cPtr, false);
  }

  private void doRemoveRange(int fromIndex, int toIndex) {
    testJNI.PartPVector_doRemoveRange(swigCPtr, this, fromIndex, toIndex);
  }

}
