/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 4.0.1
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package mypackage;

public class ReplacementVector extends java.util.AbstractList<Replacement> implements java.util.RandomAccess {
  private transient long swigCPtr;
  protected transient boolean swigCMemOwn;

  protected ReplacementVector(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(ReplacementVector obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  @SuppressWarnings("deprecation")
  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        testJNI.delete_ReplacementVector(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public ReplacementVector(Replacement[] initialElements) {
    this();
    reserve(initialElements.length);

    for (Replacement element : initialElements) {
      add(element);
    }
  }

  public ReplacementVector(Iterable<Replacement> initialElements) {
    this();
    for (Replacement element : initialElements) {
      add(element);
    }
  }

  public Replacement get(int index) {
    return doGet(index);
  }

  public Replacement set(int index, Replacement e) {
    return doSet(index, e);
  }

  public boolean add(Replacement e) {
    modCount++;
    doAdd(e);
    return true;
  }

  public void add(int index, Replacement e) {
    modCount++;
    doAdd(index, e);
  }

  public Replacement remove(int index) {
    modCount++;
    return doRemove(index);
  }

  protected void removeRange(int fromIndex, int toIndex) {
    modCount++;
    doRemoveRange(fromIndex, toIndex);
  }

  public int size() {
    return doSize();
  }

  public ReplacementVector() {
    this(testJNI.new_ReplacementVector__SWIG_0(), true);
  }

  public ReplacementVector(ReplacementVector other) {
    this(testJNI.new_ReplacementVector__SWIG_1(ReplacementVector.getCPtr(other), other), true);
  }

  public long capacity() {
    return testJNI.ReplacementVector_capacity(swigCPtr, this);
  }

  public void reserve(long n) {
    testJNI.ReplacementVector_reserve(swigCPtr, this, n);
  }

  public boolean isEmpty() {
    return testJNI.ReplacementVector_isEmpty(swigCPtr, this);
  }

  public void clear() {
    testJNI.ReplacementVector_clear(swigCPtr, this);
  }

  public ReplacementVector(int count, Replacement value) {
    this(testJNI.new_ReplacementVector__SWIG_2(count, Replacement.getCPtr(value), value), true);
  }

  private int doSize() {
    return testJNI.ReplacementVector_doSize(swigCPtr, this);
  }

  private void doAdd(Replacement x) {
    testJNI.ReplacementVector_doAdd__SWIG_0(swigCPtr, this, Replacement.getCPtr(x), x);
  }

  private void doAdd(int index, Replacement x) {
    testJNI.ReplacementVector_doAdd__SWIG_1(swigCPtr, this, index, Replacement.getCPtr(x), x);
  }

  private Replacement doRemove(int index) {
    return new Replacement(testJNI.ReplacementVector_doRemove(swigCPtr, this, index), true);
  }

  private Replacement doGet(int index) {
    return new Replacement(testJNI.ReplacementVector_doGet(swigCPtr, this, index), false);
  }

  private Replacement doSet(int index, Replacement val) {
    return new Replacement(testJNI.ReplacementVector_doSet(swigCPtr, this, index, Replacement.getCPtr(val), val), true);
  }

  private void doRemoveRange(int fromIndex, int toIndex) {
    testJNI.ReplacementVector_doRemoveRange(swigCPtr, this, fromIndex, toIndex);
  }

}
