/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 4.0.1
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package mypackage;

public class RequestPVector extends java.util.AbstractList<Request> implements java.util.RandomAccess {
  private transient long swigCPtr;
  protected transient boolean swigCMemOwn;

  protected RequestPVector(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(RequestPVector obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  @SuppressWarnings("deprecation")
  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        testJNI.delete_RequestPVector(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public RequestPVector(Request[] initialElements) {
    this();
    reserve(initialElements.length);

    for (Request element : initialElements) {
      add(element);
    }
  }

  public RequestPVector(Iterable<Request> initialElements) {
    this();
    for (Request element : initialElements) {
      add(element);
    }
  }

  public Request get(int index) {
    return doGet(index);
  }

  public Request set(int index, Request e) {
    return doSet(index, e);
  }

  public boolean add(Request e) {
    modCount++;
    doAdd(e);
    return true;
  }

  public void add(int index, Request e) {
    modCount++;
    doAdd(index, e);
  }

  public Request remove(int index) {
    modCount++;
    return doRemove(index);
  }

  protected void removeRange(int fromIndex, int toIndex) {
    modCount++;
    doRemoveRange(fromIndex, toIndex);
  }

  public int size() {
    return doSize();
  }

  public RequestPVector() {
    this(testJNI.new_RequestPVector__SWIG_0(), true);
  }

  public RequestPVector(RequestPVector other) {
    this(testJNI.new_RequestPVector__SWIG_1(RequestPVector.getCPtr(other), other), true);
  }

  public long capacity() {
    return testJNI.RequestPVector_capacity(swigCPtr, this);
  }

  public void reserve(long n) {
    testJNI.RequestPVector_reserve(swigCPtr, this, n);
  }

  public boolean isEmpty() {
    return testJNI.RequestPVector_isEmpty(swigCPtr, this);
  }

  public void clear() {
    testJNI.RequestPVector_clear(swigCPtr, this);
  }

  public RequestPVector(int count, Request value) {
    this(testJNI.new_RequestPVector__SWIG_2(count, Request.getCPtr(value), value), true);
  }

  private int doSize() {
    return testJNI.RequestPVector_doSize(swigCPtr, this);
  }

  private void doAdd(Request x) {
    testJNI.RequestPVector_doAdd__SWIG_0(swigCPtr, this, Request.getCPtr(x), x);
  }

  private void doAdd(int index, Request x) {
    testJNI.RequestPVector_doAdd__SWIG_1(swigCPtr, this, index, Request.getCPtr(x), x);
  }

  private Request doRemove(int index) {
    long cPtr = testJNI.RequestPVector_doRemove(swigCPtr, this, index);
    return (cPtr == 0) ? null : new Request(cPtr, false);
  }

  private Request doGet(int index) {
    long cPtr = testJNI.RequestPVector_doGet(swigCPtr, this, index);
    return (cPtr == 0) ? null : new Request(cPtr, false);
  }

  private Request doSet(int index, Request val) {
    long cPtr = testJNI.RequestPVector_doSet(swigCPtr, this, index, Request.getCPtr(val), val);
    return (cPtr == 0) ? null : new Request(cPtr, false);
  }

  private void doRemoveRange(int fromIndex, int toIndex) {
    testJNI.RequestPVector_doRemoveRange(swigCPtr, this, fromIndex, toIndex);
  }

}
