/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 4.0.1
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package mypackage;

public class wordSearch {
  private transient long swigCPtr;
  protected transient boolean swigCMemOwn;

  protected wordSearch(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(wordSearch obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  @SuppressWarnings("deprecation")
  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        testJNI.delete_wordSearch(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public wordSearch() {
    this(testJNI.new_wordSearch(), true);
  }

  public Part searchPart(String words, PartPVector commonParts) {
    long cPtr = testJNI.wordSearch_searchPart(swigCPtr, this, words, PartPVector.getCPtr(commonParts), commonParts);
    return (cPtr == 0) ? null : new Part(cPtr, false);
  }

  public void addPart(Part part) {
    testJNI.wordSearch_addPart(swigCPtr, this, Part.getCPtr(part), part);
  }

  public void printTree() {
    testJNI.wordSearch_printTree(swigCPtr, this);
  }

}
