/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class Simple */

#ifndef _Included_Simple
#define _Included_Simple
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     Simple
 * Method:    displayHelloWorld
 * Signature: (Ljava/lang/String;)I
 */
JNIEXPORT jint JNICALL Java_Simple_displayHelloWorld
  (JNIEnv *, jobject, jstring);

#ifdef __cplusplus
}
#endif
#endif
