/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class Simple */

#ifndef _Included_Simple
#define _Included_Simple
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     Simple
 * Method:    displayHelloWorld
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_Simple_displayHelloWorld
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
