/* DO NOT EDIT THIS FILE - it is machine generated */
#include </usr/lib/jvm/java-11-oracle/include/jni.h>
/* Header for class SwingListenerDemo */

#ifndef _Included_SwingListenerDemo
#define _Included_SwingListenerDemo
#ifdef __cplusplus
extern "C" {
#endif
#ifdef __cplusplus
}
#endif
#endif
