/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class SwingListenerDemo_CustomActionListener */

#ifndef _Included_SwingListenerDemo_CustomActionListener
#define _Included_SwingListenerDemo_CustomActionListener
#ifdef __cplusplus
extern "C" {
#endif
#ifdef __cplusplus
}
#endif
#endif
