/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 3.0.12
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package mypackage;

public class Save {
  private transient long swigCPtr;
  protected transient boolean swigCMemOwn;

  protected Save(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(Save obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        testJNI.delete_Save(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public void setSavTime(SWIGTYPE_p_time_t value) {
    testJNI.Save_savTime_set(swigCPtr, this, SWIGTYPE_p_time_t.getCPtr(value));
  }

  public SWIGTYPE_p_time_t getSavTime() {
    return new SWIGTYPE_p_time_t(testJNI.Save_savTime_get(swigCPtr, this), true);
  }

  public void setFilename(strmod value) {
    testJNI.Save_filename_set(swigCPtr, this, strmod.getCPtr(value), value);
  }

  public strmod getFilename() {
    long cPtr = testJNI.Save_filename_get(swigCPtr, this);
    return (cPtr == 0) ? null : new strmod(cPtr, false);
  }

  public void setSize(int value) {
    testJNI.Save_size_set(swigCPtr, this, value);
  }

  public int getSize() {
    return testJNI.Save_size_get(swigCPtr, this);
  }

  public Save() {
    this(testJNI.new_Save(), true);
  }

}
