/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 3.0.12
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package mypackage;

public class test {
  public static SWIGTYPE_p_time_t getCurrentTime() {
    return new SWIGTYPE_p_time_t(testJNI.getCurrentTime(), true);
  }

  public static int getNUM_OF_MACHINES() {
    return testJNI.NUM_OF_MACHINES_get();
  }

  public static int getPART_NAME_SIZE() {
    return testJNI.PART_NAME_SIZE_get();
  }

  public static int getHASH_TABLE_SIZE() {
    return testJNI.HASH_TABLE_SIZE_get();
  }

  public static int getMAX_LOG_SIZE() {
    return testJNI.MAX_LOG_SIZE_get();
  }

  public static SWIGTYPE_p_time_t getMAX_FILE_AGE() {
    return new SWIGTYPE_p_time_t(testJNI.MAX_FILE_AGE_get(), true);
  }

}
